#REDIS ESSENTIALS
#redis.host=REDIS_HOST
#redis.port=REDIS_PORT
#REDIS SOFTWARE
redis.host=redis-12000.jsd-aa1.demo.redislabs.com
redis.port=12000
redis.user=default
redis.password=REDIS_PASSWORD
#REDLOCK HOSTS
lock1.redis.host=redis-14000.jsd-aa1.demo.redislabs.com
lock1.redis.port=14000
lock1.redis.user=default
lock1.redis.password=REDIS_PASSWORD
lock2.redis.host=redis-14000.jsd-aa2.demo.redislabs.com
lock2.redis.port=14000
lock2.redis.user=default
lock2.redis.password=REDIS_PASSWORD
lock3.redis.host=redis-14001.jsd-aa3.demo.redislabs.com
lock3.redis.port=14000
lock3.redis.user=default
lock3.redis.password=REDIS_PASSWORD
#LOCK CONFIG
lease.time.ms=5000
wait.time.ms=500
hold.time.ms=1000
lock.name=east-manager
#DATA CONFIG
numeric.path=$.balance
lock.name.path=$.manager
change.value=2000