cluster.name=us-virginia
#DB
redis.host=redis-12000.jsd-aa1.demo.redislabs.com
redis.port=12000
redis.user=default
redis.password=RedisGeek
#SOURCE RANDOM GENERATOR
random.def.file=./data-template-stock-trades.json
data.record.limit=100000
data.key.prefix=aa1:trades:
data.key.prefix.burst=trades:
#SEARCH INDEX
index.def.file=./index-def-trades.json
index.name=idx:trades
query.record.limit=5
query.dialect=2