#REDIS CONNECTION - Env Var or Absolute Value
redis.host=REDIS_HOST
redis.port=REDIS_PORT
redis.user=default
redis.password=REDIS_PASSWORD
#DATA LOAD
data.record.limit=500000
data.record.type=JSON
data.batch.interval=0
#SAMPLE DATA
random.def.file=./data-template-stock-trades.json
index.def.file=./index-def-trades.json
data.key.prefix=trades:
index.name=idx:trades
#SEARCH PARAMS
query.record.limit=10
query.dialect=4
search.mode=search
search.display=value
burst.mode=n
burst.count=5
burst.interval=1000
burst.start.sec=20
#CLIENT-SIDE CACHING
client.cache=false
client.cache.size=10000
client.cache.key.prefix=accounts:ACCOUNTID:
#STREAMS
streams.producer.num.threads=1
streams.topic.name=streams:trades
streams.consumer.group.name=GRP1
streams.consumer.batch.size=1000