#redis connection details
redis.host=redis-15416.c33703.us-east-1-mz.ec2.cloud.rlrcp.com
redis.port=15416
redis.user=default
redis.password=m4HcKsl0tWvGjWYcFPmHuqm30C2jwhhk
data.record.limit=250000
data.key.prefix=trades:
#threshold at which to scale the DB
db.pct.threshold=0.25
db.scale.factor=2.0
random.def.file=./data-template-stock-trades.json
#cloud SubscriptionID and DatabaseID
cloud.subscription=2430232
cloud.db=12539896