db.url=jdbc:oracle:thin:@//34.48.114.42:1521/ORCLPDB1
db.driver.name=oracle.jdbc.driver.OracleDriver
db.user=finance
db.password=finance
header.table=CREATE TABLE ACCOUNTS ( ACCOUNTID VARCHAR2(120) NOT NULL, ACC_NAME VARCHAR2(120), MANAGER VARCHAR2(120), COMMISSION_RATE INT, CASH_BALANCE INT, ACC_VALUE INT, DAY_CHANGE INT, UNREALIZED_GAIN_LOSS INT)
detail.table=CREATE TABLE ACC_POSITIONS ( POSITIONID VARCHAR2(120) NOT NULL, ACCOUNTID VARCHAR2(120) NOT NULL, CUSIP VARCHAR2(120), QUANTITY INT)
header.table.trunc=DELETE FROM ACCOUNTS
detail.table.trunc=DELETE FROM ACC_POSITIONS
#insert the PK of the header table first
header.insert=INSERT INTO ACCOUNTS (ACCOUNTID, ACC_NAME, MANAGER, COMMISSION_RATE, CASH_BALANCE, ACC_VALUE, DAY_CHANGE, UNREALIZED_GAIN_LOSS) VALUES (?,?,?,?,?,?,?,?)
detail.insert=INSERT INTO ACC_POSITIONS (ACCOUNTID, POSITIONID, CUSIP, QUANTITY) VALUES (?, ?, ?, ?)
#json attr names in the data template  file
header.json.uid=AccountID
header.json.col.names=AccountID,AccountName,Manager,CommissionRate,CashBalance,AccValue,DayChange,UnrealizedGainLoss
header.json.col.types=s,s,s,i,i,i,i,i
detail.json.arr=Positions
detail.json.col.names=PositionID,CUSIP,Quantity
detail.json.col.types=s,s,i
batch.size=1000
data.template.file=./data-template-positions.json
#for keyspace notifications, must be enabled on DB
#$redis-cli>config set notify-keyspace-events KEA
track.keys=true
track.continuous=false
key.prefix=accounts:ACCOUNTID
redis.host=REDIS_HOST
redis.port=REDIS_PORT
redis.user=default
redis.password=REDIS_PASSWORD