broker.host=localhost:9092
header.json.uid=TradeID
batch.size=1000
num.batches=100
topic.name=ipm-trades
data.template.file=./data-template-stock-trades.json
#data.template.file=./data-template-comcast-orders.json