redis.streams.max.length=10
redis.streams.max.allowed=10
redis.streams.pending.msg.count=10
redis.streams.consumer.read.count=10
redis.streams.consumer.block.count=0
redis.streams.consumer.read.ack=false